#############################################################################
# Makefile for building: imgAnnotation.app/Contents/MacOS/imgAnnotation
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue Apr 14 17:37:44 2015
# Project:  imgAnnotation.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile imgAnnotation.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DNO_OPENCV -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -Isrc -Isrc/tmp -Isrc/ui -F/usr/local/Cellar/qt/4.8.6/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.6/lib -L/usr/local/Cellar/qt/4.8.6/lib -framework QtGui -L/usr/local/Cellar/qt/4.8.6/lib -F/usr/local/Cellar/qt/4.8.6/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = src/tmp/

####### Files

SOURCES       = src/AnnotationsPixmapWidget.cpp \
		src/functions.cpp \
		src/ImageExtractDialog.cpp \
		src/ImgAnnotations.cpp \
		src/main.cpp \
		src/MainWindow.cpp \
		src/PixmapWidget.cpp \
		src/ScrollAreaNoWheel.cpp src/tmp/moc_AnnotationsPixmapWidget.cpp \
		src/tmp/moc_ImageExtractDialog.cpp \
		src/tmp/moc_MainWindow.cpp \
		src/tmp/moc_PixmapWidget.cpp \
		src/tmp/moc_ScrollAreaNoWheel.cpp
OBJECTS       = src/tmp/AnnotationsPixmapWidget.o \
		src/tmp/functions.o \
		src/tmp/ImageExtractDialog.o \
		src/tmp/ImgAnnotations.o \
		src/tmp/main.o \
		src/tmp/MainWindow.o \
		src/tmp/PixmapWidget.o \
		src/tmp/ScrollAreaNoWheel.o \
		src/tmp/moc_AnnotationsPixmapWidget.o \
		src/tmp/moc_ImageExtractDialog.o \
		src/tmp/moc_MainWindow.o \
		src/tmp/moc_PixmapWidget.o \
		src/tmp/moc_ScrollAreaNoWheel.o
DIST          = /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		imgAnnotation.pro
QMAKE_TARGET  = imgAnnotation
DESTDIR       = 
TARGET        = imgAnnotation.app/Contents/MacOS/imgAnnotation

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile imgAnnotation.app/Contents/PkgInfo imgAnnotation.app/Contents/Resources/empty.lproj imgAnnotation.app/Contents/Info.plist $(TARGET)

$(TARGET): src/ui/ui_ImageExtractDialog.h src/ui/ui_MainWindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) imgAnnotation.app/Contents/MacOS/ || $(MKDIR) imgAnnotation.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: imgAnnotation.pro  /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile imgAnnotation.pro
/usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile imgAnnotation.pro

imgAnnotation.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) imgAnnotation.app/Contents || $(MKDIR) imgAnnotation.app/Contents 
	@$(DEL_FILE) imgAnnotation.app/Contents/PkgInfo
	@echo "APPL????" >imgAnnotation.app/Contents/PkgInfo
imgAnnotation.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) imgAnnotation.app/Contents/Resources || $(MKDIR) imgAnnotation.app/Contents/Resources 
	@touch imgAnnotation.app/Contents/Resources/empty.lproj
	
imgAnnotation.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) imgAnnotation.app/Contents || $(MKDIR) imgAnnotation.app/Contents 
	@$(DEL_FILE) imgAnnotation.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,imgAnnotation,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/Info.plist.app >imgAnnotation.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) src/tmp/imgAnnotation1.0.0 || $(MKDIR) src/tmp/imgAnnotation1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) src/tmp/imgAnnotation1.0.0/ && $(COPY_FILE) --parents src/AnnotationsPixmapWidget.h src/functions.h src/ImageExtractDialog.h src/ImgAnnotations.h src/MainWindow.h src/PixmapWidget.h src/ScrollAreaNoWheel.h src/geometry/Box.h src/geometry/Point.h src/geometry/Size.h src/numeric/functions.h src/tmp/imgAnnotation1.0.0/ && $(COPY_FILE) --parents src/AnnotationsPixmapWidget.cpp src/functions.cpp src/ImageExtractDialog.cpp src/ImgAnnotations.cpp src/main.cpp src/MainWindow.cpp src/PixmapWidget.cpp src/ScrollAreaNoWheel.cpp src/tmp/imgAnnotation1.0.0/ && $(COPY_FILE) --parents src/ImageExtractDialog.ui src/MainWindow.ui src/tmp/imgAnnotation1.0.0/ && (cd `dirname src/tmp/imgAnnotation1.0.0` && $(TAR) imgAnnotation1.0.0.tar imgAnnotation1.0.0 && $(COMPRESS) imgAnnotation1.0.0.tar) && $(MOVE) `dirname src/tmp/imgAnnotation1.0.0`/imgAnnotation1.0.0.tar.gz . && $(DEL_FILE) -r src/tmp/imgAnnotation1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r imgAnnotation.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: src/tmp/moc_AnnotationsPixmapWidget.cpp src/tmp/moc_ImageExtractDialog.cpp src/tmp/moc_MainWindow.cpp src/tmp/moc_PixmapWidget.cpp src/tmp/moc_ScrollAreaNoWheel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) src/tmp/moc_AnnotationsPixmapWidget.cpp src/tmp/moc_ImageExtractDialog.cpp src/tmp/moc_MainWindow.cpp src/tmp/moc_PixmapWidget.cpp src/tmp/moc_ScrollAreaNoWheel.cpp
src/tmp/moc_AnnotationsPixmapWidget.cpp: src/PixmapWidget.h \
		src/AnnotationsPixmapWidget.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/AnnotationsPixmapWidget.h -o src/tmp/moc_AnnotationsPixmapWidget.cpp

src/tmp/moc_ImageExtractDialog.cpp: src/ui/ui_ImageExtractDialog.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/ImageExtractDialog.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/ImageExtractDialog.h -o src/tmp/moc_ImageExtractDialog.cpp

src/tmp/moc_MainWindow.cpp: src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/MainWindow.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/MainWindow.h -o src/tmp/moc_MainWindow.cpp

src/tmp/moc_PixmapWidget.cpp: src/PixmapWidget.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/PixmapWidget.h -o src/tmp/moc_PixmapWidget.cpp

src/tmp/moc_ScrollAreaNoWheel.cpp: src/ScrollAreaNoWheel.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/ScrollAreaNoWheel.h -o src/tmp/moc_ScrollAreaNoWheel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: src/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) src/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: src/ui/ui_ImageExtractDialog.h src/ui/ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui/ui_ImageExtractDialog.h src/ui/ui_MainWindow.h
src/ui/ui_ImageExtractDialog.h: src/ImageExtractDialog.ui
	/usr/local/Cellar/qt/4.8.6/bin/uic src/ImageExtractDialog.ui -o src/ui/ui_ImageExtractDialog.h

src/ui/ui_MainWindow.h: src/MainWindow.ui
	/usr/local/Cellar/qt/4.8.6/bin/uic src/MainWindow.ui -o src/ui/ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

src/tmp/AnnotationsPixmapWidget.o: src/AnnotationsPixmapWidget.cpp src/AnnotationsPixmapWidget.h \
		src/PixmapWidget.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/AnnotationsPixmapWidget.o src/AnnotationsPixmapWidget.cpp

src/tmp/functions.o: src/functions.cpp src/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/functions.o src/functions.cpp

src/tmp/ImageExtractDialog.o: src/ImageExtractDialog.cpp src/ImageExtractDialog.h \
		src/ui/ui_ImageExtractDialog.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/PixmapWidget.h \
		src/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/ImageExtractDialog.o src/ImageExtractDialog.cpp

src/tmp/ImgAnnotations.o: src/ImgAnnotations.cpp src/ImgAnnotations.hpp \
		src/ImgAnnotations.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/ImgAnnotations.o src/ImgAnnotations.cpp

src/tmp/main.o: src/main.cpp src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/main.o src/main.cpp

src/tmp/MainWindow.o: src/MainWindow.cpp src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/functions.h \
		src/ImageExtractDialog.h \
		src/ui/ui_ImageExtractDialog.h \
		src/AnnotationsPixmapWidget.h \
		src/PixmapWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/MainWindow.o src/MainWindow.cpp

src/tmp/PixmapWidget.o: src/PixmapWidget.cpp src/PixmapWidget.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/PixmapWidget.o src/PixmapWidget.cpp

src/tmp/ScrollAreaNoWheel.o: src/ScrollAreaNoWheel.cpp src/ScrollAreaNoWheel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/ScrollAreaNoWheel.o src/ScrollAreaNoWheel.cpp

src/tmp/moc_AnnotationsPixmapWidget.o: src/tmp/moc_AnnotationsPixmapWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_AnnotationsPixmapWidget.o src/tmp/moc_AnnotationsPixmapWidget.cpp

src/tmp/moc_ImageExtractDialog.o: src/tmp/moc_ImageExtractDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_ImageExtractDialog.o src/tmp/moc_ImageExtractDialog.cpp

src/tmp/moc_MainWindow.o: src/tmp/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_MainWindow.o src/tmp/moc_MainWindow.cpp

src/tmp/moc_PixmapWidget.o: src/tmp/moc_PixmapWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_PixmapWidget.o src/tmp/moc_PixmapWidget.cpp

src/tmp/moc_ScrollAreaNoWheel.o: src/tmp/moc_ScrollAreaNoWheel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_ScrollAreaNoWheel.o src/tmp/moc_ScrollAreaNoWheel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

